//protobuf file syntax

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: api/proto/bloom.proto

// package name for the protobuf file

package bloom_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BloomService_CreateFilter_FullMethodName = "/bloom.BloomService/CreateFilter"
	BloomService_Add_FullMethodName          = "/bloom.BloomService/Add"
	BloomService_Check_FullMethodName        = "/bloom.BloomService/Check"
)

// BloomServiceClient is the client API for BloomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BloomServiceClient interface {
	// spin up a new filter
	CreateFilter(ctx context.Context, in *CreateFilterRequest, opts ...grpc.CallOption) (*CreateFilterResponse, error)
	// Add an item to the active filter
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// Check if an item is in the active filter
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
}

type bloomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBloomServiceClient(cc grpc.ClientConnInterface) BloomServiceClient {
	return &bloomServiceClient{cc}
}

func (c *bloomServiceClient) CreateFilter(ctx context.Context, in *CreateFilterRequest, opts ...grpc.CallOption) (*CreateFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFilterResponse)
	err := c.cc.Invoke(ctx, BloomService_CreateFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloomServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, BloomService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloomServiceClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, BloomService_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BloomServiceServer is the server API for BloomService service.
// All implementations must embed UnimplementedBloomServiceServer
// for forward compatibility.
type BloomServiceServer interface {
	// spin up a new filter
	CreateFilter(context.Context, *CreateFilterRequest) (*CreateFilterResponse, error)
	// Add an item to the active filter
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// Check if an item is in the active filter
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	mustEmbedUnimplementedBloomServiceServer()
}

// UnimplementedBloomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBloomServiceServer struct{}

func (UnimplementedBloomServiceServer) CreateFilter(context.Context, *CreateFilterRequest) (*CreateFilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFilter not implemented")
}
func (UnimplementedBloomServiceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedBloomServiceServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedBloomServiceServer) mustEmbedUnimplementedBloomServiceServer() {}
func (UnimplementedBloomServiceServer) testEmbeddedByValue()                      {}

// UnsafeBloomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BloomServiceServer will
// result in compilation errors.
type UnsafeBloomServiceServer interface {
	mustEmbedUnimplementedBloomServiceServer()
}

func RegisterBloomServiceServer(s grpc.ServiceRegistrar, srv BloomServiceServer) {
	// If the following call panics, it indicates UnimplementedBloomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BloomService_ServiceDesc, srv)
}

func _BloomService_CreateFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomServiceServer).CreateFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomService_CreateFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomServiceServer).CreateFilter(ctx, req.(*CreateFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloomService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloomService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloomServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloomService_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloomServiceServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BloomService_ServiceDesc is the grpc.ServiceDesc for BloomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BloomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bloom.BloomService",
	HandlerType: (*BloomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFilter",
			Handler:    _BloomService_CreateFilter_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _BloomService_Add_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _BloomService_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/bloom.proto",
}
